version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: comment-service
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_URI}
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - '8000:8000'
  redis:
    image: redis:latest
    container_name: redis-comment-service
    ports:
      - '6349:6349'
    volumes:
      - redis:/data
volumes:
  mongo:
  redis: